<?php


/**
 * Listen for conversation directed at, or around, the bot.
 *
 * @param $data
 *   The regular $data object prepared by the IRC library.
 * @param $from_query
 *   Boolean; whether this was a queried request.
 */
function chuck_bot_irc_msg_channel($data, $from_query = FALSE) {
  $to = $from_query ? $data->nick : $data->channel;
  $addressed = bot_name_regexp();

  // if message contain "ChuckxxxxNorris"
  if(preg_match("#chuck(.*?)norris#i", $data->message)) {
    $fact= html_entity_decode(chuck_api_simple_fact(),ENT_QUOTES,'UTF-8');
    $message = strip_tags($fact);
    bot_message($to,$message); // maintain user case!
  }

  
}
